# Generated by Django 4.1.7 on 2023-03-14 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_another_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='another_model',
        ),
    ]
