# Generated by Django 4.1.7 on 2023-03-15 01:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_recipe_categories_alter_recipe_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='create_at',
            field=models.DateField(default=datetime.datetime(2023, 3, 15, 1, 4, 41, 980798, tzinfo=datetime.timezone.utc)),
        ),
    ]
