# Generated by Django 4.1.7 on 2023-03-17 02:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_recipe_create_at_alter_review_rating_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='review_rating',
            name='create_at',
            field=models.DateField(default=datetime.datetime(2023, 3, 17, 2, 51, 30, 742471, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='create_at',
            field=models.DateField(default=datetime.datetime(2023, 3, 17, 2, 51, 30, 733470, tzinfo=datetime.timezone.utc)),
        ),
    ]
