# Generated by Django 4.1.7 on 2023-03-20 02:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_recipe_create_at_alter_review_rating_create_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allergies_ingrediets',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_ingrediets',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='create_at',
            field=models.DateField(default=datetime.datetime(2023, 3, 20, 2, 38, 32, 381247, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='review_rating',
            name='create_at',
            field=models.DateField(default=datetime.datetime(2023, 3, 20, 2, 38, 32, 388235, tzinfo=datetime.timezone.utc)),
        ),
    ]
