# Generated by Django 4.1.7 on 2023-03-20 05:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_recipe_create_at_alter_review_rating_create_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_allergy_ingrediets',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='create_at',
            field=models.DateField(default=datetime.datetime(2023, 3, 20, 5, 20, 58, 546385, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review_rating',
            name='create_at',
            field=models.DateField(default=datetime.datetime(2023, 3, 20, 5, 20, 58, 558832, tzinfo=datetime.timezone.utc)),
        ),
    ]
