# Generated by Django 4.1.7 on 2023-03-20 05:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_recipe_recipe_allergy_ingrediets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_favorite_ingrediets',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='create_at',
            field=models.DateField(default=datetime.datetime(2023, 3, 20, 5, 27, 30, 408531, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='review_rating',
            name='create_at',
            field=models.DateField(default=datetime.datetime(2023, 3, 20, 5, 27, 30, 415512, tzinfo=datetime.timezone.utc)),
        ),
    ]
