# Generated by Django 4.1.7 on 2023-03-21 16:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_collectionname_collectionimg_alter_recipe_create_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collections',
            name='collection_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections_collection_name', to='base.collectionname'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='create_at',
            field=models.DateField(default=datetime.datetime(2023, 3, 21, 16, 49, 2, 445096, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='review_rating',
            name='create_at',
            field=models.DateField(default=datetime.datetime(2023, 3, 21, 16, 49, 2, 461088, tzinfo=datetime.timezone.utc)),
        ),
    ]
