# Generated by Django 4.1.7 on 2023-03-22 00:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_alter_recipe_create_at_alter_review_rating_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='create_at',
            field=models.DateField(default=datetime.datetime(2023, 3, 22, 0, 59, 53, 470991, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='review_rating',
            name='create_at',
            field=models.DateField(default=datetime.datetime(2023, 3, 22, 0, 59, 53, 479919, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterUniqueTogether(
            name='collectionname',
            unique_together={('user', 'collection_name')},
        ),
    ]
